import Head from 'next/head'
import Link from 'next/link'
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <title>TTBFW</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.cardHolder}>
        <h1>Table Top Book Framework</h1>

        <div className={styles.card}>
          <Link href="/example">
            <a>Example of components</a>
          </Link>
        </div>

        <div className={styles.card}>
          <Link href="/pathfinder">
            <a>Pathfinder</a>
          </Link>
        </div>

        <div className={styles.card}>
          <Link href="/vampire-the-masquerade">
            <a>Vampire the Masquerade</a>
          </Link>
        </div>
      </div>
    </div>
  )
}
