import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>TTBFW</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Table Top Book Framework</h1>

      <ul>
        <li>
          <Link href="/example">
            <a>Example of components</a>
          </Link>
        </li>
        <li>
          <Link href="/pathfinder">
            <a>Pathfinder</a>
          </Link>
        </li>
        <li>
          <Link href="/vampire-the-masquerade">
            <a>Vampire the Masquerade</a>
          </Link>
        </li>
      </ul>
    </div>
  )
}
